### ISSUE TITLE
Handle typedef of opaque structs 

### ISSUE THREAD

**Issue by biozic** [jacob-carlborg/dstep#107]
When an opaque struct is defined in a C header like that:
```c
    typedef struct foo foo;
```
no symbols are generated in the .d file. It only works if the name of the struct is not the same as the typedef. The output should be:
```d
   struct foo;
```

**Comment by ciechowoj** [comment]
Yeah, that's embarrassing.

**Comment by ciechowoj** [comment]
I should fix it in a moment.
