### ISSUE TITLE
Option --space-after-function-name doesn't work with function pointer syntax

### ISSUE THREAD

**Issue by biozic** [jacob-carlborg/dstep#116]
I think it's a recent change.
```c
int foo(void);

typedef int (*Fun0)(void);
typedef int (*Fun1)(int (*param)(void));

struct Foo {
  int (*bar)(void);
};
```
when run with `--space-after-function-name=false`, gives:
```d
int foo();

alias Fun0 = int function ();
alias Fun1 = int function (int function () param);

struct Foo
{
    int function () bar;
}
```

**Comment by ciechowoj** [comment]
I understand that the problem is superfluous space after `function` keyword, right?

**Comment by biozic** [comment]
Yes, that's it. IRC, it was handled the same way as function declarations until recently. But maybe it's a feature.

**Comment by ciechowoj** [comment]
You are probably right, that space should be removed.
