### ISSUE TITLE
Builds fine on Fedora Rawhide, but not on Debian Sid

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#134]
Using "dub build --compiler=ldc2" master builds fine on Fedora Rawhide, which has Clang/LLVM 4.0, and only this version. Debian Sid however supports having a plethora of Clang/LLVM versions, currently 3.8, 3.9, 4.0, and 5.0. It appears that -lclang is only meaningful if you have the default Clang/LLVM package installed – which is 3.8.

Is there an easy way of getting DStep to link to -lclang-3.9 or something like that?

**Comment by jacob-carlborg** [comment]
On Debian and Ubuntu, if you install the dev packages you'll get a symlink that is called `libclang.so`. This will be installed in `/usr/lib/llvm-<version>/lib`, which is not a standard library search path. What you can do is either modify `dub.json` to add this path here [1] or you can set the environment variable `LIBRARY_PATH`, if I recall correctly.

I'm working on a better way to handle all these different installation locations #105.

[1] https://github.com/jacob-carlborg/dstep/blob/master/dub.json#L32

**Comment by russel** [comment]
I tried a symbolic link from a directory in LD_LIBRARY_PATH but that didn't work since Dub doesn't include that in the link path. It sounds though as there is no point in following this up yet, Debian has LLVM 3.8, 3.9, 4.0, and 5.0 (I choose 3.9) but these are not 3.7 and so things won't work.

For now I'll build a D module manually as needed.

**Comment by jacob-carlborg** [comment]
I think that DStep will work with 3.8 as well. It was 3.9 that broke that API, IIRC.

**Comment by jacob-carlborg** [comment]
Isn't `LD_LIBRARY_PATH` used to look for libraries when running the application? And `LIBRARY_PATH` when linking the application?

**Comment by russel** [comment]
Yes indeed. I have set stuff up wrongly! However, I am not sure I want to revert to 3.8 on Debian given I have 4.0 on Fedora. But this is my problem.

**Comment by russel** [comment]
As far as I can tell none of the Debian packages cause /usr/lib/libclang.so to appear. I got a build with LLVM 3.9 by fiddling with symbolic links and environment variables, but:
```
|> dstep -o LibDVBv5 /usr/include/libdvbv5/dvb-fe.h
Illegal instruction
```
But then 3.9 is not actually supported so, at least for now, this is a null comment.

**Comment by jacob-carlborg** [comment]
> As far as I can tell none of the Debian packages cause /usr/lib/libclang.so to appear

Yeah, I guess to support multiple version of the same library.

> But then 3.9 is not actually supported so, at least for now, this is a null comment.

3.8 has been reported to work. It was 3.9 that introduced the breaking change.

**Comment by russel** [comment]
I relented and installed libclang 3.8 and set up the hack to create a libclang.so so Dub works and I got a build on Debian *and* it appears to be working. :-)

Now to find out how many of the libdvbv5 header files I have to list to get a reasonable libdvbv5.d module.

**Comment by jacob-carlborg** [comment]
> I relented and installed libclang 3.8 and set up the hack to create a libclang.so so Dub works and I got a build on Debian and it appears to be working. :-)

Nice.

**Comment by jacob-carlborg** [comment]
> Now to find out how many of the libdvbv5 header files I have to list to get a reasonable libdvbv5.d module.

Let me know if you need any more help.

**Comment by russel** [comment]
I think I am now in the "DStep lots of files till I get enough to be able to write the channel scanner in D" which is definitely playing on my part till stuff works – unless I find some actual translation problems. Since I now have a build on Debian despite Debian and Dub, and we know DStep will not work on Fedora till LLVM 4.0 is supported in DStep, I think it time to close this issue. Thanks for the feedback and help, most useful.

**Comment by jacob-carlborg** [comment]
> Thanks for the feedback and help, most useful.

Cool, no worries 😃 .
