### ISSUE TITLE
Error on Fedora Rawhide

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#135]
DStep build fine:
```
|> dstep --version
v0.2.2-164-g4e574fe
```
but when I tried to use it (assuming I am not being an idiot and using it wrongly)
```
|> dstep -o libdvbv5.d /usr/include/libdvbv5/*.h
dstep: an unknown error occurred: core.exception.AssertError@dstep/translator/Type.d(518): Unhandled type kind cast(CXTypeKind)119
----------------
core.exception.AssertError@dstep/translator/Type.d(518): Unhandled type kind cast(CXTypeKind)119
----------------
```

**Comment by jacob-carlborg** [comment]
I'm assuming you're using libclang 3.9 or later, which broke the API. DStep officially only supports libclang 3.7 as the latest version. This has already been reported here https://github.com/jacob-carlborg/dstep/issues/98.

**Comment by jacob-carlborg** [comment]
BTW, we're working on fixing this.
