### ISSUE TITLE
struct member expansion

### ISSUE THREAD

**Issue by saivert** [jacob-carlborg/dstep#137]
I have a struct:
```c
// FILE object wrapper for vfs access
typedef struct {
    struct DB_vfs_s *vfs;
} DB_FILE;
```

dstep now looks up `struct DB_vfs_s` and expands this inside the parent struct while eating all comments before the definition of `struct DB_vfs_s`. Leading to something like:
```d
// FILE object wrapper for vfs access
struct DB_FILE
{
    // md5 calc control structure (see md5/md5.h)

    // bps must be 32 if this is true

    // lots more comments

    struct DB_vfs_s
    {
        DB_plugin_t plugin;

        // capabilities
        const(char*)* function () get_schemes; // NULL-terminated list of supported schemes, e.g. {"http://", "ftp://", NULL}; can be NULL

```
and so on...

This is a workaround (C code):
```c
typedef struct DB_vfs_s DB_vfs_t;
// FILE object wrapper for vfs access
typedef struct DB_FILE_s {
    DB_vfs_t *vfs;
} DB_FILE;
```
but seems like dstep should cope with using struct notation without expanding it inline.

**Comment by jacob-carlborg** [comment]
Running the following file through DStep master:

```c
// FILE object wrapper for vfs access
typedef struct {
    struct DB_vfs_s *vfs;
} DB_FIL
```

Givens the following result:

```d
// FILE object wrapper for vfs access

extern (C):

struct DB_FILE
{
    struct DB_vfs_s;
    DB_vfs_s* vfs;
}
```

That looks correct to me. Are you using a pre-compiled release? Because those are quite old and o lot has happened since then.

**Comment by saivert** [comment]
I'm running v0.2.2-164-g4e574fe

**Comment by jacob-carlborg** [comment]
Hmm, seems like you have the latest.

**Comment by jacob-carlborg** [comment]
Does your header file contain some more code that perhaps causes this problem?

**Comment by saivert** [comment]
Full source is here: https://github.com/Alexey-Yakovenko/deadbeef/blob/master/deadbeef.h

**Comment by jacob-carlborg** [comment]
Hmm, ok. This occurs if the struct used in a field is declared after the struct it's used in.
