### ISSUE TITLE
Repeated declarations cause problems

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#138]
In /usr/include/libdvbv5/dvb-fe.h there are two instances of:
```
extern const unsigned fe_bandwidth_name[8];
```
in the C (and C++) header files this is not a problem (though I am going to report this as a bug). This leads to two lines:
```
extern __gshared const(uint)[8] fe_bandwidth_name;
```
in the generated by DStep dvb_fe.d. Sadly this leads to compilation errors:
```
generated/dvb_fe.d(782): Error: variable dvb_fe.fe_bandwidth_name conflicts with variable dvb_fe.fe_bandwidth_name at generated/dvb_fe.d(775)
```
Is this a bug in DStep or a bug in ldc2?

**Comment by jacob-carlborg** [comment]
> in the C (and C++) header files this is not a problem.

Hmm, interesting.

> Is this a bug in DStep or a bug in ldc2?

It's a bug in DStep.

**Comment by russel** [comment]
I have emailed the the list on which the libdvbv5 people operate to try and get a fix. Even if they fix tomorrow and release, it will be ages before it gets to mainstream distributions. And given the glacial speed of progress of the Travis-CI folk it may get there by 2038.

**Comment by jacob-carlborg** [comment]
Ok, I see. But it's definitely a bug in DStep. I didn't know this was allowed in C code. Is it due to `extern`?

**Comment by russel** [comment]
As far as I am aware you can any number of declarations for a symbol in C and C++ as long as they are mutually consistent. Only if a declaration disagrees with a previous declaration is it an error.

It turns out you have to be able to do this because of #include.

**Comment by jacob-carlborg** [comment]
> It turns out you have to be able to do this because of #include.

Right, that makes sense.

**Comment by jacob-carlborg** [comment]
> As far as I am aware you can any number of declarations for a symbol in C and C++ as long as they are mutually consistent.

Seems to only apply to functions without a body and `extern` variables, at least in a C source file.

**Comment by jacob-carlborg** [comment]
I'm mean, isn't that why include guards are used?

**Comment by russel** [comment]
Many header files may have to include forward declarations, so given the arbitrary code created by an include tree you can end up with many forward declaration is the compilation. This is very true in the libdvbv5 code, lots of forward declarations, many include files.
