### ISSUE TITLE
Building on Fedora Rawhide doesn't find libclang.so

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#150]
(I know DStep won't work with LLVM 4.0 as is on Rawhide as at 2017-06-12, but…)

I tried a build of DStep on Fedora Rawhide, using the command:

    dub build --compiler=ldc2 --build=release

Three instances of:
```
## Warning for package dstep, configuration default ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

-m32mscoff: Use --arch=x86/--arch=x86_64/--arch=x86_mscoff to specify the target architecture
```
which is bizarre isn't that all about Windows building? Then:
```
Running pre-generate commands for dstep...
Performing "release" build using ldc2 for x86_64.
dstep 0.2.2+commit.176.gb99a764: building configuration "default"...
Running pre-build commands...
object.Exception@configure.d(295): Could not find libclang.so in any of the standard paths for llvm: 
/usr/lib/llvm-4.0/lib
/usr/lib/llvm-3.9/lib
/usr/lib/llvm-3.8/lib
/usr/lib/llvm-3.7/lib
/usr/lib
/usr/local/lib
/usr/lib/x86_64-linux-gnu
Please specify a path manually using './configure --llvm-path=<path>'.
----------------
Program exited with code 1
/usr/bin/ld: cannot find @linker_flags.txt: No such file or directory
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
ldc2 failed with exit code 1.
```
As far as I know Fedora always uses `/usr/lib64` for libraries such as `libclang.so` perhaps it could be added to the search path?

**Comment by jacob-carlborg** [comment]
> As far as I know Fedora always uses /usr/lib64 for libraries such as libclang.so perhaps it could be added to the search path?

Sure, but it's not expected that DStep will find libclang on *all* distributions, that's why the flag is available.

**Comment by russel** [comment]
No worries, I just thought the search list looked very Debian.

**Comment by jacob-carlborg** [comment]
I was thinking that I would start by supporting Debian and CentOS and that would cover quite a few distributions, but libclang in CentOS is really old so I didn't bother adding that.

**Comment by jacob-carlborg** [comment]
@russel do I need to worry about 32bit? I guess that won't have a directory called `lib64`.

**Comment by russel** [comment]
CentOS is just Fedora, only old. :-)  Fedora, CentOS, and RHEL all have the same.
```
/usr/lib64
/usr/lib32
```
Personally I have no problem with ignoring 32-bit, but I am but one in the set of people working with DStep.

**Comment by jacob-carlborg** [comment]
> CentOS is just Fedora, only old. :-) Fedora, CentOS, and RHEL all have the same.

I installed Clang on CentOS 7 using Docker, it installs libclang in `/usr/lib64/llvm/`, so it's not exactly the same.

**Comment by russel** [comment]
I thought they were…I thought wrong. Apologies.

**Comment by jacob-carlborg** [comment]
I think that Fedora is so far ahead of CentOS that it starts to be difficult to treat them as the same.

**Comment by BorisCarvajal** [comment]
Can this issue be revisited?

The root LLVM directory is never used alone, only after "/lib" gets appended ([configure.d#L83]).
Why not pass the LLVM library dir or even the full .so path to the script?

In Gentoo, 64-bit libs were moved to "/lib64" directory in newer multilib profiles (including llvm internal structure as I see) . "/lib" dir now contains cross-arch stuff and 32-bit libs.

[configure.d#L83]: https://github.com/jacob-carlborg/dstep/blob/master/configure.d#L83

**Comment by jacob-carlborg** [comment]
> The root LLVM directory is never used alone, only after "/lib" gets appended (configure.d#L83).
Why not pass the LLVM library dir

The idea was that if DStep used more things from LLVM than just libclang the use would only need to pass one path.

> or even the full .so path to the script?

I didn't know that was possible with dynamic libraries.

> In Gentoo, 64-bit libs were moved to "/lib64" directory in newer multilib profiles (including llvm internal structure as I see) . "/lib" dir now contains cross-arch stuff and 32-bit libs.

So what's the full path to libclang? `/lib64/libclang.so`? Where are the other files located, like the internal headers? These are located in `lib/clang/<version>/include` in the archive available at http://releases.llvm.org.

**Comment by BorisCarvajal** [comment]
> I didn't know that was possible with dynamic libraries.

I was meaning something like --llvm-libs-path

> So what's the full path to libclang? /lib64/libclang.so? Where are the other files located, like the internal headers? 

/usr/lib/llvm/9/lib64/libclang.so
/usr/lib/llvm/9/include/clang/
/usr/lib/clang/9.0.0/include/  <-- low level stuff like avx2intrin.h

I'll pull code to get the directory using "llvm-config --libdir".
