### ISSUE TITLE
Falling back to blunt pre-processor phase

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [jacob-carlborg/dstep#154]
Experimenting with new dstep features regarding pre-processor (i.e. alias / function translation) I have found it to be causing too much trouble for D1 compatibility case to try patching it. Is there a simple way to disable it (by flag or something) to just run pre-processor blindly same as in earlier dstep versions? 

Mostly @ciechowoj question I presume.

**Comment by ciechowoj** [comment]
You mean you want to disable pre-processing of macros completely?

**Comment by ciechowoj** [comment]
Just out of curiosity could you give some examples of what would be needed?

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah in old dstep versions it run actual C pre-processor first and only did conversion to D after (== no symbolic constants or type aliases from defines, everything expanded literally). Would be good to have such behaviour as a fallback option available in cases where smart translation fails for any reason.

**Comment by ciechowoj** [comment]
I looked into the code, and adding such a feature seems as simple as adding single if in one place (and appropriate command to CLI). In particular add the if to `translateMacroDefinition` function from `Translator.d.`... I'll create PR when I have some spare time.
