### ISSUE TITLE
Segmentation fault!

### ISSUE THREAD

**Issue by trikko** [jacob-carlborg/dstep#175]
I'm trying to convert bson.h from github repository [1], to update my mongo library.
This command:

`dstep -DBSON_COMPILATION -I/usr/include/clang/4.0.0/include -I/home/andrea/src/D/lib/mondo/mongo-c-driver/src/libbson/src/bson/ /home/andrea/src/D/lib/mondo/mongo-c-driver/src/libbson/src/bson/bson.h -o /tmp/tmp_binding.d
`

ends with a segmentation fault.

[1] https://github.com/mongodb/libbson

**Comment by ciechowoj** [comment]
Can you provide your copy of the library somewhere? I've tried the one from the link and it works...

**Comment by jacob-carlborg** [comment]
Same here. I wasn't able to reproduce the issue. Which version of DStep are you using?

**Comment by trikko** [comment]
I tried with a couple of different version. No way.

**Comment by trikko** [comment]
Hmm it works if I compile from git master.
Maybe precompiled versions doesn't work well with my clang libraries?

**Comment by jacob-carlborg** [comment]
The precompiled binaries are ridiculously old, like two years. There's been a huge amount of improvements, bug fixes an new features. I'm working on releasing a new version, including precompiled binaries.

And no, the precompiled versions are probably limited to work with Clang 3.7.
