### ISSUE TITLE
Build fails on Debian Sid

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#183]
I am at master and:
```
|> dub build --compiler=ldc2 --build=release
Running pre-generate commands for dstep...
Performing "release" build using ldc2 for x86_64.
dstep 0.2.2+commit.232.gc8fc7a3: building configuration "default"...
Running pre-build commands...
/usr/bin/ld: cannot find -lclang
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
ldc2 failed with exit code 1.
```
I am nt sure what fix to suggest since the DStep blurb says libclang 3.9 but the linker file appears to try and find libclang 3.8.

**Comment by jacob-carlborg** [comment]
I need the following information:

* Which versions of LLVM/libclang are installed?
* How are they installed?
* Where are they installed?
* What's the content of `linker_flags.txt`

Or, even better, if you can provide a Dockerfile that reproduces the issue.

BTW, what do you mean with `DStep blurb`?

**Comment by russel** [comment]
Everything installed via Debian packages:
```
|> aptitude search libclang | grep ^i
i A libclang-4.0-dev - clang library - Development package
i A libclang-common-3.8-dev - clang library - Common development package
i A libclang-common-3.9-dev - clang library - Common development package
i A libclang-common-4.0-dev - clang library - Common development package
i A libclang-common-5.0-dev - clang library - Common development package
i  libclang-dev - clang library - Development package
i A libclang1-3.8 - C interface to the clang library
i A libclang1-3.9 - C interface to the clang library
i A libclang1-4.0 - C interface to the clang library
i A libclang1-5.0 - C interface to the clang library
```
The linker_flags.txt is the one in the repository:
```
|> more linker_flags.txt 
-L/usr/lib/llvm-3.8/lib
-lclang
-Xlinker -rpath /usr/lib/llvm-3.8/lib
```
I will have to admit to having no idea how to do anything with Docker.

The README states:
```
#### Requirements

* libclang - [http://clang.llvm.org](http://clang.llvm.org) - 3.9.0
…
```

**Comment by jacob-carlborg** [comment]
Do you have all of those versions of libclang installed?

**Comment by jacob-carlborg** [comment]
> The linker_flags.txt is the one in the repository

`linker_flags.txt` is generated by a pre-build step which tries to automatically find an appropriate version of libclang.

**Comment by russel** [comment]
It seems that the combination of packages I want requires all of those versions to be installed.

OK, the bug is that the linker_flags.txt file is not removed. I deleted it and now have a fine build.
```
|> more linker_flags.txt 
-L/usr/lib/llvm-4.0/lib
-lclang
-Xlinker -rpath /usr/lib/llvm-4.0/lib
```
well, assuming dstep works when built with libclang-4.0. :-)

**Comment by jacob-carlborg** [comment]
> OK, the bug is that the linker_flags.txt file is not removed. I deleted it and now have a fine build.

That's intentional. The idea is that one can invoke the `configure` script manually if it fails to find libclang automatically.

> well, assuming dstep works when built with libclang-4.0. :-)

4.0 is officially supported. For the full set of officially supported version of libclang, have a look at the Travis CI script [1].

[1] https://github.com/jacob-carlborg/dstep/blob/master/.travis.yml#L15-L17

**Comment by jacob-carlborg** [comment]
Can we close this issue?
