### ISSUE TITLE
dub.json preGenerateCommand fails from dub package

### ISSUE THREAD

**Issue by Timoses** [jacob-carlborg/dstep#185]
When doing 

```
dub fetch dstep
dub build dstep
```
it fails because the package (~/.dub/packages/dstep-0.2.3/dstep) is not a git directory. The dub.json contains:
```
"preGenerateCommands": [
    "cd \"$PACKAGE_DIR\" && git describe --tags > resources/VERSION"
],
```

Any other way to fetch the version when no git is available? Perhaps from the foldername `dstep-0.2.3`? 

Initially reported here: https://github.com/dlang/dub/issues/1391

**Comment by jacob-carlborg** [comment]
There's no other way to get the exact same behavior. The `resources/VERSION` file could be checked in, containing a hard coded version. But then any commits between releases would not affect the version, as it does today.

**Comment by Timoses** [comment]
What if a released version (commit with release tag) contains a VERSION with the version.

e.g.:
```
"preGenerateCommands": [
    "cd \"$PACKAGE_DIR\" && [[ -d .git ]] && git describe --tags > resources/VERSION"
],
```

And with a new version (new tag) the tag is written into `resources/VERSION` (which is tracked with the git repo).

I'm not sure how `dub fetch` works. Does it fetch from the git repo (specified version) and simply discards the `git` directory?
Question then would arise what happens if version `~master` is specified in dub.

**Comment by jacob-carlborg** [comment]
Not sure I understand.

**Comment by Timoses** [comment]
I'm not sure either..

I'm assuming that dub fetches the package from the git repository:
https://code.dlang.org/packages/dstep/versions

```
"preGenerateCommands": [
    "cd \"$PACKAGE_DIR\" && [[ -d .git ]] && git describe --tags > resources/VERSION"
],
```
prevents the call to git if the package folder is not a git repo. This is the case when doing `dub fetch dstep`.

This means that the VERSION would need to be written and added to the commit with every new commit for both
* commits to a branch (could be simply the branch name)
* version releases (tagging)

### For commits to a branch
A simple `pre-commit` git hook (https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks#_committing_workflow_hooks) could be run to add the version to the `resources/VERSION` file and add the file so it is committed.

This works for the branches, so a fetched `~<branch>` version would have the branch name in `VERSION`.

### For new releases / tagging
Not sure how this could work since a release commit will probably be tagged after the commit itself is done. This means the commit cannot be changed so the `VERSION` can't be set appropriately.
Perhaps a script could help which does the following (given it is passed the new version as an argument):
`release.sh v0.2.4`:
* write v0.2.4 to `resources/VERSION`
* `git add resources/VERSION`
* `git commit -m "Release v0.2.4"`
* `git tag v0.2.4`

### Why?
I was looking for a simple way to use dub to fetch and run dstep. It would allow the following
`dub fetch dstep && dub build dstep`
`ln -s ~/.dub/packages/dstep-<version>/dstep/bin/dstep /usr/local/bin/`
providing a simple way to install it to the system.

However, the fetched package is not a git repo which is why the build fails...

**Comment by mihails-strasuns** [comment]
@jacob-carlborg what you can do is to commit dummy `VERSION` with content "unknown" to the repo and modify dub script like @Timoses has proposed:

```
"preGenerateCommands": [
    "cd \"$PACKAGE_DIR\" && [[ -d .git ]] && git describe --tags > resources/VERSION"
]
```

Effective behaviour would be to use correct version when dstep is built from git repo but also make building possible (with "unknown" version string) for anyone who wants to fetch/run it via dub.

It may need another version of that command for Windows though.


> I'm assuming that dub fetches the package from the git repository

@Timoses  Nope, it doesn't. It stores own source acrhive for each version when package is published (it is possible to publish packages that have not repo at all).

**Comment by jacob-carlborg** [comment]
> what you can do is to commit dummy VERSION with content "unknown" to the repo

That might be acceptable. But then the `VERSION` file would be changed every time it's built with Git being available.

**Comment by mihails-strasuns** [comment]
On a fresh clone, yes. Is that a problem somehow?

**Comment by jacob-carlborg** [comment]
> On a fresh clone, yes.

As far as I can see it would always be changed.

> Is that a problem somehow?

It's not ideally. It can be accidentally committed.

**Comment by mihails-strasuns** [comment]
You can output it on the fly in that case, something like:
```
 "cd \"$PACKAGE_DIR\" && [[ -d .git ]] && git describe --tags > resources/VERSION" || echo \"unknown\" > resources/VERSION"
```

**Comment by Timoses** [comment]
> It's not ideally. It can be accidentally committed.

See "**For commits to a branch**" in my previous post.

You would add the version file to the tracked files. During building dub would write the `git describe ...` version to the file.

However, when commiting, with the `pre-commit hook` you would always write the `resources/VERSION` file before commiting to reflect the current branch. So you wouldn't accidentally commit a "wrong" version to the branch.

To prevent the hook to overwrite the version when tagging/releasing (see "**For new releases / tagging**") change the commit command in release.sh to:
```
git commit -m "Release v0.2.4" --no-verify
```
`--no-verify` skips the pre-commit hook.

I adjusted the commit line in my previous post (otherwise the hook would overwrite the written version).

**Comment by mihails-strasuns** [comment]
Pre-commit hooks don't work because you can't configure that on dev machine of everyone who clones dstep. Post-commit hook would work, but GitHub doesn't support those afaik.

**Comment by Timoses** [comment]
That complicates things. Was not aware that hooks are not part of the repository : /.

**Comment by mihails-strasuns** [comment]
Do you see any problem with solution I have proposed here - https://github.com/jacob-carlborg/dstep/issues/185#issuecomment-369355354 ?

**Comment by Timoses** [comment]
Actually, it would be really handy if there was a `$PACKAGE_VERSION` in the dub.json [environment variables](http://code.dlang.org/package-format?lang=json#environment-variables).

Issue with request exists:
https://github.com/dlang/dub/issues/1302

**Comment by jacob-carlborg** [comment]
@mihails-strasuns I haven't been able to find something that works on Windows.

**Comment by mihails-strasuns** [comment]
Well, that would have be a separate script, right (branched on platform). But it should be more or less same (don't have windows machine right now to actually check)

```bat
IF EXIST .git (
git describe --tags > resources/VERSION
) ELSE (
echo unknwon > resources/VERSION
)
```

**Comment by jacob-carlborg** [comment]
Well, it's not like I haven't googled it and tried both Powershell and the regular cmd 😃. I've already tried the above.

**Comment by mihails-strasuns** [comment]
:grumpy:

I will see if I can find something when I get to a Windows machine.

**Comment by Timoses** [comment]
Just as a note: There's a `DUB_PACKAGE_VERSION` variable now which might be useful!
