### ISSUE TITLE
struct declarations create a type?

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#189]
Simplifying, I have two modules a.d and b.d that result from a DStep run. a.d has a struct definition, for example:
```d
struct X {
…
}
```
and in b.d there is:
```d
struct X;
```
This seems to create two different types: a.X and b.X. I find I have to remove the declaration in b.d and add an import statement to get the types correct.

Is this expected?

**Comment by ciechowoj** [comment]
Yes, as dstep currently translates the modules separately. But this is defect obviously.

**Comment by mihails-strasuns-sociomantic** [comment]
See also https://github.com/jacob-carlborg/dstep/issues/101 (essentially duplicate)

**Comment by russel** [comment]
Curses, libdvbv5 has a plethora of `struct X;` declarations all over the place. I'll comment them all out and add an appropriate import for each symbol `X`. Sad, but I understand given the current state of DStep.

**Comment by jacob-carlborg** [comment]
DStep has a `--skip` flag to skip generate bindings for the specified symbol.

**Comment by russel** [comment]
I can't think how to use it effectively: the problem is to know which file not to use this option with. I shall cogitate further.

**Comment by jacob-carlborg** [comment]
Right, I guess you would need to explicitly figure that out and the invoke DStep with different flags for different files.

**Comment by russel** [comment]
Options are to find the problem and then amend the script to cope (the sensible way) or hack it manually afterwards (what I have just done). I will retrofit the script using the data, now that I have it!

**Comment by russel** [comment]
I wonder if it is time to close this issue, given that #101 exists.

**Comment by jacob-carlborg** [comment]
Closing as duplicate of https://github.com/jacob-carlborg/dstep/issues/101.
