### ISSUE TITLE
Flagging an issue with #define

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#190]
DStep turns:
```c
#define dvb_desc_ca_field_last  privdata
```
into:
```
enum dvb_desc_ca_field_last = privdata;
```
However in this case the C `#define` is really just for string editing – to give a sensible name to a badly named struct field: privdata is the name of the field in the struct and dvb_desc_ca_field_last is the more sensible name that should have been used.

I suspect there is no sensible thing for DStep to do here, but I am flagging this (somewhat bizarre) use of `#define` in real life C code.

**Comment by jacob-carlborg** [comment]
Seems (almost) impossible for DStep to figure out what to do here.

**Comment by ciechowoj** [comment]
What about checking if privdata is a type and translating is accordingly?

**Comment by russel** [comment]
I had that feeling, but I thought it worth asking the question.

I am comfortable with this one having to be a manual hack since the result of DStep will almost always result in a compilation error, so the problem should always be flagged and not slip through.

**Comment by jacob-carlborg** [comment]
> What about checking if privdata is a type and translating is accordingly?

That would assume `privdata` is in scope. What would it do if it's not a type?

**Comment by ciechowoj** [comment]
Sorry I didnt notice that its the field and not the type, we are actually
handling the types correctly...

Then it trickier to do anything about it...
