### ISSUE TITLE
Add a command line option to add extra imports.

### ISSUE THREAD

**Issue by yshui** [jacob-carlborg/dstep#198]
Something close to `--global-attribute`, but for imports.

**Comment by jacob-carlborg** [comment]
I would prefer that DStep could output the necessary imports automatically.

**Comment by yshui** [comment]
It is really hard to completely cover everything.

**Comment by jacob-carlborg** [comment]
Sure, I'll see if this can be added, shouldn't be that difficult.

**Comment by jacob-carlborg** [comment]
Fixed in https://github.com/jacob-carlborg/dstep/commit/ce739b772ce9676e285b59e227b7379557504017.
