### ISSUE TITLE
#define (simplest cases only?)

### ISSUE THREAD

**Issue by aldanor** [jacob-carlborg/dstep#20]
I'm sorry if this has already been brought up but I haven't found it in issues or docs: can preprocessor directives like `#define` be handled? It looks like they can't. I'm not too familiar with libclang so this may well be something obvious.

Aside from dealing with compile time flags, most of the C libraries use `#define` to set constants, as in `#define X (1)`, `#define Y ((float)-X)`, which easily transforms to `immutable`. For a large percentage of headers, just handling constants would be sufficient to get them working.

However, C-defines can get ugly, weird and unpredictable and sure there's no way to handle all of them... though some can be parsed into immutable constants, some into functions `#define f(a, b) ((a) + (b))`.

Are there any plans regarding this?

Thanks.

**Comment by ciechowoj** [comment]
I suppose it could be closed via #67 . However I may create a file `Issue20.d` with unit tests with the few examples of defines mentioned here.

**Comment by jacob-carlborg** [comment]
@ciechowoj should I close it now or do you want me to wait for the unit tests?

**Comment by ciechowoj** [comment]
Actually it was question for you, but I'll add unit tests first : )
