### ISSUE TITLE
C INT_MAX not handled

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#204]
Using DStep v0.2.3-16-g1308991 compiled on Debian Sid with LDC 1.11.0 and LLVM 6.0, I generated a module for fontconfig.h (version 2.13.0). Sadly:
```
generated/fontconfig.d(257): Error: undefined identifier INT_MAX
generated/fontconfig.d(576): Error: undefined identifier stat_
```
I am not sure where the `stat_` is creeping in. The generated D is:
```d
FcCache* FcDirCacheLoadFile (const(FcChar8)* cache_file, stat_* file_stat);
```

**Comment by russel** [comment]
I believe s/INT_MAX/int.max/ does the job for the first error.

**Comment by ciechowoj** [comment]
There was a bug preventing dstep from including `core.stdc.limits`. Regarding `stat_` the dstep was confused by the fact that stat library has two symbols with the same name `struct stat` and function `stat`, after translation `struct ` is removed so there is ambiguity...
