### ISSUE TITLE
Issues when compiling for Windows

### ISSUE THREAD

**Issue by ZILtoid1991** [jacob-carlborg/dstep#205]
It compiles and links, but I get this error message when I try to execute the application:

dstep.exe - Entry Point Not Found

The procedure entry point clang_Type_getNamedType could not be located in the dynamic link library <path to the file>\dstep.exe

Is there any way to fix this or to distribute a binary instead of relying on the end-user for compiling?

**Comment by jacob-carlborg** [comment]
> The procedure entry point clang_Type_getNamedType could not be located in the dynamic link library \dstep.exe

Which version of libclang are you using? Latest supported version is 4.0.0.

> Is there any way to fix this or to distribute a binary instead of relying on the end-user for compiling?

Yes. I'm working on that. Should be ready soon.

**Comment by ZILtoid1991** [comment]
Still nothing with 4.0.0...

**Comment by ciechowoj** [comment]
Can you copy the clang .dll to the directory with dstep? Maybe it's using the wrong .dll (from you system directory or something...).

**Comment by ZILtoid1991** [comment]
Thanks, it now works with libclang.dll in the same directory.

You might want to add this information to your readme.md if someone else might encounter with the same problem.

**Comment by ZILtoid1991** [comment]
Also it only mentions LLVM, not the versions it was tested with.
