### ISSUE TITLE
can't alias to existing D type

### ISSUE THREAD

**Issue by chriscamacho** [jacob-carlborg/dstep#216]
when translating the header from https://github.com/ggambetta/libz80

dstep emitted the following code (in part)

`alias ushort = ushort;`
`alias byte = ubyte;`

fortunately its not a large header so I could just comment these alias's out and change any byte to ubyte ...

**Comment by ciechowoj** [comment]
@chriscamacho The first case is easy to fix - just ignore the alias, but what about the second case? Do you think having dstep to automatically convert `byte` to `ubyte` would solve the problem?

**Comment by jacob-carlborg** [comment]
This looks like a case where DStep doesn't handle D keywords. A quick fix would be to just suffix the alias names with `_` as we do in other places.

**Comment by chriscamacho** [comment]
although in the C world _ is supposed to be reserved I haven't honestly seen it in practice, I'd say an initial scan to prefix any D keywords in the C source with _ or similar would be a good approach and would probably solve other undiscovered corner cases lurking to catch you out !

**Comment by jacob-carlborg** [comment]
We're currently adding a suffix, not a prefix, i.e `byte` -> `byte_`.

**Comment by ciechowoj** [comment]
Yes, I guess the pragmatic approach with _ is fine. But it doesn't look 'nice', I'm wondering if renaming all bytes to ubytes isn't a better approach...

**Comment by chriscamacho** [comment]
what if its not actually unsigned ?

**Comment by jacob-carlborg** [comment]
> I'm wondering if renaming all bytes to ubytes isn't a better approach...

That seems quite brittle. What if `byte` is part of the API and now that symbol doesn't exist anymore and cannot be used by users of the binding.

**Comment by jacob-carlborg** [comment]
> what if its not actually unsigned ?

Or not corresponding to D's `ubyte` but it's instead a typedef for `int` or whatever. (We need to account for stupid things).

**Comment by ciechowoj** [comment]
If it's not actually unsigned then we can just ignore the alias as in the case of ushort above.

**Comment by jacob-carlborg** [comment]
What about code like this: `typedef int byte`?

**Comment by ciechowoj** [comment]
Yes, I would rename it only if it's form like in current bug. The stupid cases have to be resolved by other means (_ suffix for example).

**Comment by ciechowoj** [comment]
Or in case of typedef int byte, rename all the bytes to ints

**Comment by ciechowoj** [comment]
I wouldn't worried about the symbols, if naming of the types influenced the mangling we are screwed with any renaming (e.g. adding _). I don't think the aliases to primitive types are exported at all.

**Comment by jacob-carlborg** [comment]
I'm not worried about mangling. What I'm referring to is if the C header defines a symbol called `byte` and then the user tries to code like `byte a = 0;`, `byte` won't exist. But I guess we have the same problem with adding `_`.

**Comment by jacob-carlborg** [comment]
I guess the best would be to check all the usages of the typedef and then translate to what the typedef resolves to. This could be bundled in the existing `--reduce-aliases` flag.
