### ISSUE TITLE
Dub assumes default installation path for LLVM on Windows

### ISSUE THREAD

**Issue by GoaLitiuM** [jacob-carlborg/dstep#224]
Building dstep on Windows fails when LLVM is installed to somewhere else than the default installation directory.

The build instructions should be corrected for Windows builds as there seems to be no attemps to discover where the LLVM is installed, it is only assumed to be installed under ``C:\Program Files\LLVM`` (which is also a hardcoded path, ``"/LIBPATH:$PROGRAMFILES\\LLVM\\lib"`` should be used instead for `lflags-windows`).

**Comment by jacob-carlborg** [comment]
I can't get `$PROGRAMFILES` to work. It contains spaces and the linker doesn't seem to like that: https://ci.appveyor.com/project/jacob-carlborg/dstep/build/job/d75tsc612x7sb2aj.

**Comment by GoaLitiuM** [comment]
It seems to be a bug in DMD, LDC passes the fully quoted `LIBPATH` to linker just fine, but DMD seems to drop them somewhere in the way.

**Comment by jacob-carlborg** [comment]
I reported a bug: https://issues.dlang.org/show_bug.cgi?id=19821.

**Comment by GoaLitiuM** [comment]
There was actually an existing report about the same bug dated few years back: https://issues.dlang.org/show_bug.cgi?id=16677

**Comment by jacob-carlborg** [comment]
I could use `$PROGRAMFILES` for LDC, if that's useful?

**Comment by GoaLitiuM** [comment]
I think the mention about the installation path in README should be enough for now.
