### ISSUE TITLE
generate module declaration

### ISSUE THREAD

**Issue by Basile-z** [jacob-carlborg/dstep#225]
They are required by some tools that won't work properly if not present.

**Comment by jacob-carlborg** [comment]
There’s the `—package` flag. Does that help?

**Comment by Basile-z** [comment]
Yeah for the use case this works, but I suppose that an option to use the filename would be preferable in some cases, for example when the filename uses <prefix>underscore<name> as naming scheme.

**Comment by jacob-carlborg** [comment]
So a way to specify the module name without the package name?

**Comment by Basile-z** [comment]
I suggest the feature at least. But Once again right now, for the stuff I converted, `--package <name>` works fine.

**Comment by jacob-carlborg** [comment]
I’m just trying to understand what you’re suggesting 😊

**Comment by Basile-z** [comment]
let's say that this is okat. #226 is more a real issue.
