### ISSUE TITLE
Automatically detect macOS SDK path

### ISSUE THREAD

**Issue by jacob-carlborg** [jacob-carlborg/dstep#227]
Currently DStep assumes that header files are available in `/usr/include` or any of the other standard Unix paths. By default Xcode will not install anything in those path, instead the SDK path can be obtained using `xcrun --show-sdk-path`.

**Comment by Robert-M-Muench** [comment]
Which gives something like:
````
| => xcrun --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
````
and from there one can find `.../usr/include`
