### ISSUE TITLE
Are there plans to include dstep in the official toolchain ?

### ISSUE THREAD

**Issue by Basile-z** [jacob-carlborg/dstep#236]
Are there plans to include dstep in the official toolchain ?

**Comment by jacob-carlborg** [comment]
I wouldn't mind that. I was planning to ask the leadership about that but now when Attila is taking over from Andrei maybe he prefers his dpp.

**Comment by Basile-z** [comment]
I haven't tested dpp for now but I wonder if it's adapted to all situations, for example what I had to do for firm.

**Comment by Basile-z** [comment]
Not to speak about code completion... having the d header is pretty much the only way.

**Comment by jacob-carlborg** [comment]
I can ask anyway.
