### ISSUE TITLE
dstep dumps core on a simple header

### ISSUE THREAD

**Issue by tbrowder** [jacob-carlborg/dstep#26]
Given a file t.h, with contents:

extern const char *const sys_errlist[];

Run dstep on it and get a core dump:

$ dstep -x c -o t.d t.c
Segmentation fault (core dumped)

I built dtep from this repo on a Debian Linux 64-bit system (after building and installing the dmd suite from its repos).

**Comment by rlonstein** [comment]
(bump)

Any chance of this being fixed?

**Comment by jacob-carlborg** [comment]
Yes, of course. I'll see if I can get it fixed during the weekend.

**Comment by jacob-carlborg** [comment]
I haven't actually fixed this yet (I have worked improving the test infrastructure) but I can only reproduce this with libclang 3.4.x. Version 3.1-3.3 and 3.5.0 seems to be ok.

**Comment by rlonstein** [comment]
I'll test on Linux and report back. Thanks.

**Comment by rlonstein** [comment]
Works as expected.
