### ISSUE TITLE
Crashes if fed nonexistent header

### ISSUE THREAD

**Issue by joakim-noah** [jacob-carlborg/dstep#28]
At least with the prebuilt dstep 0.1.0-2 on Arch, it crashes and spits out a backtrace if I feed it a non-existent C header, such as if I add a typo in the header's path.  It'd be nice if it issued an error instead, so the user knows what he did wrong.

**Comment by ciechowoj** [comment]
@joakim-noah I know that it was long ago, but by 'header' you mean a header file for translation (an argument for dstep), right?

**Comment by joakim-noah** [comment]
Yes, I mistyped the path for the input C header file and Dstep segfaulted on the invalid path.
