### ISSUE TITLE
unknown type name 'size_t'

### ISSUE THREAD

**Issue by Tooniis** [jacob-carlborg/dstep#284]
Trying to dstep http://source.netsurf-browser.org/libsvgtiny.git/tree/include/svgtiny.h:

```
/usr/include/svgtiny.h:68:23: error: unknown type name 'size_t'
```

**Comment by jacob-carlborg** [comment]
This is a known limitation. Please see the readme under "Limitations/Known issues", the last point [1].

[1] https://github.com/jacob-carlborg/dstep#limitationsknown-issues
