### ISSUE TITLE
Missing `__u/int128` support

### ISSUE THREAD

**Issue by kassane** [jacob-carlborg/dstep#288]
Source to translate:
https://github.com/tigerbeetle/tigerbeetle/blob/main/src/clients/c/tb_client.h

`typedef __uint128_t tb_uint128_t;` -> `alias tb_uint128_t = <unimplemented>;`

The translation gave an undefined type.

https://github.com/jacob-carlborg/dstep/blob/2cb53c131c18d1d94d7f4fc2896305dd4154763a/dstep/translator/Type.d#L188-L196

**Comment by jacob-carlborg** [comment]
D doesn't support 128bit integers. What do you suggest the result would be?

**Comment by kassane** [comment]
> D doesn't support 128bit integers

https://dlang.org/phobos/core_int128.html ?

**Comment by kassane** [comment]
In my test `core.int128` not working in DMD2:
https://d.godbolt.org/z/n3bG75d3K

LDC and GDC works!

```bash
<source>(9): Error: module `int128` is in file 'core/int128.d' which cannot be read
import path[0] = /opt/compiler-explorer/dmd2-nightly/dmd2/linux/bin64/../../src/phobos
import path[1] = /opt/compiler-explorer/dmd2-nightly/dmd2/linux/bin64/../../src/druntime/import
Compiler returned: 1
```

**Comment by jacob-carlborg** [comment]
Strange, it's available in the repository. BTW, have you checked if it's ABI compatible with `__uint128_t`?

**Comment by kassane** [comment]
> Strange, it's available in the repository. BTW, have you checked if it's ABI compatible with `__uint128_t`?

More recent information is below:
- https://github.com/dlang/dmd/pull/14768

**Comment by jacob-carlborg** [comment]
BTW, should it be `core.int128` or `std.int128`?

**Comment by kassane** [comment]
> BTW, should it be `core.int128` or `std.int128`?

Please, use `core.int128`! Added the `Cent` to my wrapper and it's fine during the test.

**Comment by jacob-carlborg** [comment]
I'm not that familiar with 128 bit integers, but it seems there's no unsigned version in `core.int128`?

**Comment by kassane** [comment]
> I'm not that familiar with 128 bit integers, but it seems there's no unsigned version in `core.int128`?

I know. Not ideal, but for some simulated operations so far haven't had any problems.

I tried using uint64 with high values ​​during concurrent transactions and in some cases I applied the use of integer casts.

Then I will publish the D client to compare with the C Client as a reference.
I need to better integrate Zig's event-loop (libtbClient) with D concurrency (appClient).

**Comment by jacob-carlborg** [comment]
Do you suggest using the signed `Cent` for both signed and unsigned?

**Comment by kassane** [comment]
> Do you suggest using the signed `Cent` for both signed and unsigned?

It's not ideal, but yeah. Using Cent in signed and unsigned.

**Comment by jacob-carlborg** [comment]
@kassane is this what you had in mind: https://github.com/jacob-carlborg/dstep/commit/ac4b87638d5bb83624105fa7e9c04f10b8657d73#diff-9347ce4d022101ff02a5f37861df6934dc17bd9a72590f391f603a555f6e10b8?

**Comment by kassane** [comment]
Exactly.
