### ISSUE TITLE
Don't name anonymous enums

### ISSUE THREAD

**Issue by joakim-noah** [jacob-carlborg/dstep#29]
D allows them, so I had to search-and-replace to get the Anonymous_x names out.

**Comment by ciechowoj** [comment]
There is some problem with translating a corner case. Consider following code:

```
enum {
    FOO,
    BAR,
} baz;
````

D doesn't allow such a construction, so the enum is required to have explicit name, on the other side the enum items are still visible in global space. The best thing I can think of at the moment is to declare `baz` as `int`.

**Comment by ciechowoj** [comment]
The best solution would be to name the enum and still export its items to the global scope.

**Comment by jacob-carlborg** [comment]
Yeah, just through an alias.

**Comment by ciechowoj** [comment]
Could you provide an example ?

**Comment by ciechowoj** [comment]
Do you mean to repeat all the enumeration items as the aliases in global scope?

**Comment by jacob-carlborg** [comment]
```d
enum  _Anonymous_0
{
    FOO,
    BAR
}

alias FOO = _Anonymous_0.FOO;
alias BAR = _Anonymous_0.BAR;
```

**Comment by ciechowoj** [comment]
Well, this can be done.
