### ISSUE TITLE
Structs with a terminating flexible array member trigger a segfault

### ISSUE THREAD

**Issue by joakim-noah** [jacob-carlborg/dstep#35]
For example, this simple header file will get dstep to segfault:

```C
struct foobar {
    int state;
    int info[];
};
```

Removing the brackets on the last member will get dstep to work again, [some info on flexible array members](https://www.securecoding.cert.org/confluence/display/seccode/void+MEMxx-C.+Understand+how+flexible+array+members+are+to+be+used).

**Comment by joakim-noah** [comment]
[As I just noted in the forum](http://forum.dlang.org/thread/mailman.33.1247093746.14071.digitalmars-d@puremagic.com?page=2#post-wbvejavjgatpbrwxirzd:40forum.dlang.org), it appears the right way to translate this would be to `int[0] info;`.

**Comment by jacob-carlborg** [comment]
That should be straightforward to implement.
