### ISSUE TITLE
Regression: clang 3.5 causes struct members to be defined again

### ISSUE THREAD

**Issue by joakim-noah** [jacob-carlborg/dstep#36]
I recently ran dstep from Arch and found that the output is different.  Since the dstep package hasn't been updated, I'm guessing the update from clang 3.4 to 3.5 caused this regression.  Here's a test header file I came up with to demonstrate the problem:

```C
struct foo { int x; int y;};

struct bar { struct foo a; struct foo b;};
```

And the D output dstep produces:

```D
extern (C):

struct foo
{
        int x;
        int y;
}

struct bar
{
        struct foo
        {
                int x;
                int y;
        }
        foo a;
        struct foo
        {
                int x;
                int y;
        }
        foo b;
}
```

There's no reason to define the struct again twice, not sure why it's doing that.

**Comment by mihails-strasuns-sociomantic** [comment]
Don't have old clang to see how it worked before but right now the problem is how libclang reports cursors:

```D
struct foo { }; // CXCursor_StructDecl

struct foo var; // CXCursor_VarDecl

struct bar // CXCursor_StructDecl
{
    struct foo var; // CXCursor_StructDecl
}
```

I am looking for a way to distinguish that latter `CXCursor_StructDecl` is not really a struct declaration based on cursor metadata but nothing obvious seems to match.

**Comment by mihails-strasuns-sociomantic** [comment]
One option cold be to store list of all definition cursors (http://clang.llvm.org/doxygen/group__CINDEX__CURSOR__XREF.html#gafcfbec461e561bf13f1e8540bbbd655b) and check it before outputing a new one.

**Comment by mihails-strasuns-sociomantic** [comment]
This may be related, global struct variables are also generated wrong:
```C
struct zzz { };

extern struct zzz x;
```
into
```D
extern (C):

extern __gshared zzz x;

struct zzz
{
}
```

**Comment by mihails-strasuns-sociomantic** [comment]
#37

**Comment by jacob-carlborg** [comment]
@mihails-strasuns-sociomantic `struct foo var` is not reported as a `CXCursor_FieldDecl` when inside a struct?

**Comment by jacob-carlborg** [comment]
> Don't have old clang to see how it worked before but right now

If you want to, you can run `dub --config=test` which will download a couple of versions of libclang and run the whole test suite. The actual test suite requires Ruby and two gems.

**Comment by mihails-strasuns-sociomantic** [comment]
> struct foo var is not reported as a CXCursor_FieldDecl when inside a struct?

@jacob-carlborg it is, but is also reported as `CXCursor_StructDecl` - with a cursor referencing real definition. See linked PR.
