### ISSUE TITLE
spurious generation of variadic args rather than implicit void ie () argument list

### ISSUE THREAD

**Issue by Laeeth** [jacob-carlborg/dstep#38]
converting the mathgl headers

I got:
double mgl_rnd_ (...);

but it should just be:
double mgl_rnd();

hope this is not something simple I am doing wrong.  sorry, but I have not time right now to find the original header and try to replicate it.

**Comment by jacob-carlborg** [comment]
I'm using quite an old version of Clang now, but I can only get this to compile in C++ mode. DStep does not support C++.

**Comment by Laeeth** [comment]
It's one of those strange cases where there is a pure C API documented in the headers but it is mixed in with C++.  So  dstep did an okay job, but got confused on those small cases.

**Comment by jacob-carlborg** [comment]
I'll need to investigate how AST in libclang looks like.
