### ISSUE TITLE
Recognise and translate __attribute__((__packed__))

### ISSUE THREAD

**Issue by w0rp** [jacob-carlborg/dstep#39]
In GCC  and LLVM, you can declare a packed struct like so.

```typedef struct __attribute__((__packed__)) { /* */ } name;```

This is equilvalent to the following in D.

```struct name { align(1): /* */ }```

I would like it if dstep would recognise the former and translate it into the latter. Otherwise, it will output structs with the wrong alignment.

**Comment by jacob-carlborg** [comment]
Should be possible as long as it's accessible from the libclang API.

**Comment by w0rp** [comment]
Nice. I had forgotten that I had even raised this issue. Hopefully that will be useful for someone in future.
