### ISSUE TITLE
Compile failure with DMD v2.0.68

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [jacob-carlborg/dstep#42]
I get an error when compiling with DMD v2.068. Just changing tango dependency to `1.0.3+2.068` seems to fix the issue.

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks!

**Comment by MyLittleRobo** [comment]
Please also release the new version, so dstep could be run with dub:
```
dub fetch dstep
dub run dstep
```

Current version in dub package registry has these building errors.

**Comment by jacob-carlborg** [comment]
Sure, no problem.

**Comment by jacob-carlborg** [comment]
@MyLittleRobo pushed v0.2.0.
