### ISSUE TITLE
Generating code that will not compile

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#46]
This is a one off case but…

The C code:

struct dtv_property {
	__u32 cmd;
	__u32 reserved[3];
	union {
		__u32 data;
		struct dtv_fe_stats st;
		struct {
			__u8 data[32];
			__u32 len;
			__u32 reserved1[3];
			void *reserved2;
		} buffer;
	} u;
	int result;
} __attribute__ ((packed));

results in the D code:

struct dtv_property
{
    __u32 cmd;
    __u32[3] reserved;
    union
    {
        __u32 data;
        struct dtv_fe_stats
        {
            __u8 len;
            dtv_stats[4] stat;
        }
        dtv_fe_stats st;
        struct
        {
            __u8[32] data;
            __u32 len;
            __u32[3] reserved1;
            void* reserved2;
        }
    }
    int result;
}

which is compile error not only because of the __u32 and __u8 types, but because of the field data in the anonymous struct.

I do not have any answers, but I think this marker for the problems needs to be put on record.

**Comment by jacob-carlborg** [comment]
You mean because `buffer` and `u` is removed?

**Comment by russel** [comment]
Indeed. removal of the buffer and u flattens the name space and creates a conflict over the name data that wasn't there before.

Also __u32 and __u8 are not being converted to their D forms.

**Comment by jacob-carlborg** [comment]
What are `__u32` and `__u8`? If they're `#define` than they will not be handled.
