### ISSUE TITLE
Spits out <unimplemented> for function-typed parameter

### ISSUE THREAD

**Issue by rcorre** [jacob-carlborg/dstep#49]
The following:

    void freeAll(void (freeFunc)(void*));

is translated to

    void freeAll (<unimplemented> freeFunc);

Instead of

    void freeAll (void function(void*) freeFunc);

**Comment by jacob-carlborg** [comment]
Shouldn't there be a star before `freeFunc`? Isn't that a function declaration and not a function pointer?

**Comment by rcorre** [comment]
Do you mean like this?

    void freeAll(void (*freeFunc)(void*)) {

I don't think it matters, the `*` is optional. Either way, its a declaration of a function that takes a function pointer as an argument. For reference, I'm seeing this [here](https://github.com/slembcke/Chipmunk2D/blob/master/include/chipmunk/chipmunk_private.h#L46)

**Comment by jacob-carlborg** [comment]
Yeah, `void (freeFunc)(void*)` and `void (*freeFunc)(void*)` is the same for function parameters. But not on global level in a file. What a wonderful language C is :angry:.

Turns out that the above two ways of writing function pointers have a different representations in the Clang AST.
