### ISSUE TITLE
Symbol selection

### ISSUE THREAD

**Issue by trikko** [jacob-carlborg/dstep#58]
It would be useful to have a way to pass a list of symbols to export (or ignore) from c source.

**Comment by jacob-carlborg** [comment]
Could you please elaborate on why this is useful.

**Comment by trikko** [comment]
Some cases:
- Struct I just need signature.
- Symbol inside a file but dstep force me to import all
- Ignore errors by dstep on enum/struct/functions I don't care about
- Clean binding importing only functions I need (it's easier to maintain in future)

For example check:
https://github.com/2night/mondo/blob/master/source/mongoc.d#L103
That struct it's not a valid d code. Anyway I need just its definition.

Or:
https://github.com/2night/mondo/blob/master/source/mongoc.d#L8

I need just a couple of functions from libbson to interface with libmongo, I don't care about other functions/structs from library. And if they will add function/struct/enum/typdef I don't like to have them added to my binding. For exampl symbols could be collide with existing imported symbols or generate invalid D code.

**Comment by jacob-carlborg** [comment]
I prefer to fix DStep to not generate invalid code in the first place.

**Comment by trikko** [comment]
You're right, of course. But anyway I have to write a dirty-script to fix error with a workaround. It would be better to have some options to skip them. Also to keep binding stable also if they add new things, as said. 

It would be fun to have dstep as library. I give it a source and it returns a range of translated definition/declarations. So I can filter them or merge easily. (and dstep app could be built over this library).

**Comment by ciechowoj** [comment]
What about adding `--skip` and `--skipdef` switches to CLI. The first one would remove the translated item from the output completely and the second one would remove the definition of structs (keep only the declaration). For instance:

`dstep ... --skip foo --skip bar --skip baz --skipdef _bson_value_t`

It starts to be quite long, but it would be still useful for someone who uses dstep as part of some script.

**Comment by jacob-carlborg** [comment]
`--skipdef` would translate `struct Foo { int a; }` to `struct Foo`?

**Comment by ciechowoj** [comment]
Yes, that is the idea.
