### ISSUE TITLE
Shouldn't dstep exit with status code when there is some kind of error?

### ISSUE THREAD

**Issue by ciechowoj** [jacob-carlborg/dstep#59]
Currently `dstep` always returns `0` exit code, even on the failure (wrong input file/wrong command arguments). I believe it would be better, if it returns something other (e.g. 1) when there is an error. I would make `dstep` easier to integrate with some command line tools (and make testing easier).

**Comment by jacob-carlborg** [comment]
Absolutely. It should exit with a non-zero status code if an exception has been thrown. Although, I'm not sure if an exception is thrown in all the right places.
