### ISSUE TITLE
typedef and anonymous structs

### ISSUE THREAD

**Issue by trikko** [jacob-carlborg/dstep#8]
Something like this:

typedef struct { ... } struct_name;

is a common pattern in c. It's just a way to rename an anonymous struct.

dstep split this in two different declaration

struct anonymous
{
}

and 

alias anonymous struct_name;

Original anonymous struct will be never used and can't be called from C code, so I think this two declaration can be merged in a single named struct.

**Comment by w0rp** [comment]
I saw this myself when I was converting a header. I ended up having to pick the output apart myself and set the structs in the right way.

**Comment by jacob-carlborg** [comment]
I do know it's not optimal, but it should still work?

**Comment by jacob-carlborg** [comment]
Another case where the struct has a name but only appears in a typedef:

```c
typedef struct rd_kafka_metadata {
        int         broker_cnt;     /* Number of brokers in 'brokers' */
        struct rd_kafka_metadata_broker *brokers;  /* Brokers */

        int         topic_cnt;      /* Number of topics in 'topics' */
        struct rd_kafka_metadata_topic *topics;    /* Topics */

        int32_t     orig_broker_id; /* Broker originating this metadata */
        char       *orig_broker_name; /* Name of originating broker */
} rd_kafka_metadata_t;


rd_kafka_metadata (rd_kafka_t *rk, int all_topics,
                   rd_kafka_topic_t *only_rkt,
                   const struct rd_kafka_metadata **metadatap,
                   int timeout_ms);
```

**Comment by ciechowoj** [comment]
Isn't is already fixed?

**Comment by w0rp** [comment]
I don't know myself. Try the Pebble headers. That's what I was translating at the time.
