### ISSUE TITLE
New multiline translation

### ISSUE THREAD

**Issue by dataPulverizer** [jacob-carlborg/dstep#83]
I noticed that dstep now outputs functions multi-line. I do some post processing of the dstep outputs and the new multi-line outputs would make it difficult for me to post-process the the functions outputs in the way I usually do.

**Comment by ciechowoj** [comment]
Could you elaborate? A command line switch could be added to disable putting function arguments to multiple lines.

**Comment by dataPulverizer** [comment]
Elaboration: for instance the function appears

int functioName(type1 agr1,
type2 arg2, 
type3 agr3,
...,
typeN agrN)

Yes a command line switch to disable the multi-line feature would be great, thanks.

**Comment by ciechowoj** [comment]
I've just made a PR, I hope it will be accepted : ).
